
library(ggplot2)
library(jsonlite)
library(plyr)

library(RJSONIO)
library(ggmap)
library(geosphere)
library(data.table)
library(gdata)
library(varhandle)
library(mapmate)
library(dplyr)
library(igraph)
library(network)
library(sna)
library(ndtv)
library(threejs)
library(networkD3)
library(visNetwork)
library(maps)
library(ggmap)
library(mapdata)
library(mapproj)
library(maptools)
library(RColorBrewer)
library(classInt)
#library(rgdal)
library(scales)
library(raster)
library(RBioFabric)
library(HiveR)
 
install_github("leonawicz/mapmate")
install_github("wjrl/RBioFabric")
library(mapmate)
library(RBioFabric)
